const canvas=document.getElementById('map'),ctx=canvas.getContext('2d');
const S={cash:100000,influence:10,year:1900,q:1,paused:false,speed:1,selected:null,zoom:1,panX:0,panY:0,holdings:{},factories:{},
countries:[
{id:'aurora',name:'AURORA',x:.15,y:.23,w:.23,h:.25,color:'#58684f',res:'OIL',gdp:420000,stab:78,cities:[['Port Aurora',.22,.38],['New Eden',.40,.27]]},
{id:'borealis',name:'BOREALIS',x:.43,y:.13,w:.27,h:.28,color:'#65705e',res:'IRON',gdp:310000,stab:64,cities:[['Northgate',.53,.24],['Ironhaven',.64,.34]]},
{id:'crown',name:'CROWNLAND',x:.70,y:.23,w:.22,h:.27,color:'#6b664d',res:'FOOD',gdp:510000,stab:82,cities:[['Crown City',.77,.34],['Eastport',.86,.43]]},
{id:'meridia',name:'MERIDIA',x:.27,y:.54,w:.26,h:.28,color:'#66594d',res:'IRON',gdp:270000,stab:58,cities:[['Meridian',.38,.62],['Southport',.49,.74]]},
{id:'sundar',name:'SUNDAR',x:.57,y:.57,w:.25,h:.28,color:'#596554',res:'OIL',gdp:390000,stab:71,cities:[['Sundar Bay',.67,.67],['Old Docks',.78,.78]]}
],ships:[{x:.57,y:.46,t:0},{x:.67,y:.52,t:2},{x:.48,y:.82,t:4}]};

function resize(){canvas.width=canvas.clientWidth*devicePixelRatio;canvas.height=canvas.clientHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);draw()}addEventListener('resize',resize);
function xy(x,y){let w=canvas.clientWidth,h=canvas.clientHeight;return [x*w*S.zoom+S.panX,y*h*S.zoom+S.panY]}
function polygon(c){let [x,y]=xy(c.x,c.y),w=c.w*canvas.clientWidth*S.zoom,h=c.h*canvas.clientHeight*S.zoom;return [[x+w*.06,y+h*.18],[x+w*.72,y],[x+w,y+h*.25],[x+w*.86,y+h*.88],[x+w*.35,y+h],[x,y+h*.66]]}
function draw(){
let w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);
ctx.fillStyle='#2d4039';ctx.fillRect(0,0,w,h);
ctx.strokeStyle='#3f554d';ctx.globalAlpha=.35;for(let x=0;x<w;x+=45){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=45){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.globalAlpha=1;
S.countries.forEach(c=>{let p=polygon(c);ctx.beginPath();p.forEach((a,i)=>i?ctx.lineTo(...a):ctx.moveTo(...a));ctx.closePath();ctx.fillStyle=c.color;ctx.fill();ctx.lineWidth=S.selected===c.id?3:1;ctx.strokeStyle=S.selected===c.id?'#dfc277':'#9a9b85';ctx.stroke();let cx=p.reduce((a,b)=>a+b[0],0)/p.length,cy=p.reduce((a,b)=>a+b[1],0)/p.length;ctx.fillStyle='#e5dfc5';ctx.font='bold 14px Georgia';ctx.textAlign='center';ctx.fillText(c.name,cx,cy);ctx.font='10px Arial';ctx.fillStyle='#c5c8bd';ctx.fillText('◆ '+c.res,cx,cy+17);
c.cities.forEach(city=>{let [sx,sy]=xy(city[1],city[2]);ctx.fillStyle='#d9c38a';ctx.beginPath();ctx.arc(sx,sy,4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d6d9d0';ctx.textAlign='left';ctx.fillText(city[0],sx+7,sy+3)})});
ctx.setLineDash([6,5]);ctx.strokeStyle='#bda05f';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(...xy(.40,.36));ctx.lineTo(...xy(.53,.24));ctx.lineTo(...xy(.77,.34));ctx.stroke();ctx.setLineDash([]);
S.ships.forEach((s,i)=>{let x=s.x+Math.sin(Date.now()/3000+i)*.008,y=s.y+Math.cos(Date.now()/3500+i)*.008,[sx,sy]=xy(x,y);ctx.fillStyle='#e7e0c7';ctx.beginPath();ctx.moveTo(sx-7,sy-3);ctx.lineTo(sx+8,sy);ctx.lineTo(sx-7,sy+4);ctx.closePath();ctx.fill();});
requestAnimationFrame(draw)
}
function select(id){S.selected=id;let c=S.countries.find(x=>x.id===id);document.getElementById('panelType').textContent=c.name;document.getElementById('panelBody').innerHTML=`<h2>${c.name}</h2><span class="tag">RESOURCE: ${c.res}</span><span class="tag">STABILITY: ${c.stab}%</span><div class="stat">GDP <b>${money(c.gdp)}</b></div><div class="stat">Your ownership <b>${S.holdings[id]||0}%</b></div><div class="stat">Factories <b>${S.factories[id]||0}</b></div><hr><button class="action" onclick="buy('${id}')">📈 Buy 10% of local industry — ${money(c.gdp*.08)}</button><button class="action" onclick="factory('${id}')">🏭 Build industrial complex — $20,000</button><button class="action" onclick="lobby('${id}')">🏛 Fund political influence — $8,000</button>`}
function money(n){return '$'+Math.round(n).toLocaleString('en-US')}
function buy(id){let c=S.countries.find(x=>x.id===id),cost=c.gdp*.08;if(S.cash<cost)return news('Treasury too low.');S.cash-=cost;S.holdings[id]=(S.holdings[id]||0)+10;S.influence+=10;news('ACQUISITION: You bought 10% of '+c.name+' industry.');select(id);ui()}
function factory(id){if(S.cash<20000)return news('Treasury too low.');S.cash-=20000;S.factories[id]=(S.factories[id]||0)+1;let c=S.countries.find(x=>x.id===id);c.gdp+=35000;news('INDUSTRY: A new factory opens in '+c.name+'.');select(id);ui()}
function lobby(id){if(S.cash<8000)return news('Treasury too low.');S.cash-=8000;S.influence+=6;S.countries.find(x=>x.id===id).stab-=2;news('POLITICS: Your lobby gains ground in '+S.countries.find(x=>x.id===id).name+'.');select(id);ui()}
function news(t){document.getElementById('ticker').textContent=t}
function ui(){document.getElementById('cash').textContent=money(S.cash);let inc=0;S.countries.forEach(c=>inc+=c.gdp*((S.holdings[c.id]||0)/100)*.012);document.getElementById('income').textContent=money(inc);document.getElementById('influence').textContent=Math.round(S.influence);document.getElementById('date').textContent=S.year+' Q'+S.q}
function advance(){if(S.paused)return;S.q++;if(S.q>4){S.q=1;S.year++}let inc=0;S.countries.forEach(c=>inc+=c.gdp*((S.holdings[c.id]||0)/100)*.012);S.cash+=inc;S.countries.forEach(c=>c.gdp*=.995+Math.random()*.015);if(Math.random()<.25)news(['RAILWAY BOOM: Industrial output rises.','BANKING PANIC: Investors become cautious.','TRADE WINDFALL: Commodity demand surges.','LABOR STRIKE: One region loses productivity.'][Math.floor(Math.random()*4)]);ui()}
setInterval(advance,7000);
canvas.addEventListener('click',e=>{let r=canvas.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top;for(const c of S.countries){let p=polygon(c);ctx.beginPath();p.forEach((a,i)=>i?ctx.lineTo(...a):ctx.moveTo(...a));ctx.closePath();if(ctx.isPointInPath(mx,my)){select(c.id);break}}});
document.getElementById('zoomIn').onclick=()=>S.zoom=Math.min(1.8,S.zoom+.15);document.getElementById('zoomOut').onclick=()=>S.zoom=Math.max(.7,S.zoom-.15);document.getElementById('reset').onclick=()=>{S.zoom=1;S.panX=0;S.panY=0};document.getElementById('pause').onclick=()=>{S.paused=!S.paused;document.getElementById('pause').textContent=S.paused?'▶':'Ⅱ'};document.getElementById('speed').onclick=()=>news('Time controls will be expanded in v0.3.');
document.getElementById('close').onclick=()=>{S.selected=null;document.getElementById('panelType').textContent='WORLD';document.getElementById('panelBody').innerHTML='<h1>Build your empire.</h1><p>Click a country, city, company, railway or ship. The world keeps moving while you make your fortune.</p>'};
document.querySelectorAll('.bottom button').forEach(b=>b.onclick=()=>{let t=b.dataset.tab;document.getElementById('panelType').textContent=t.toUpperCase();if(t==='companies')document.getElementById('panelBody').innerHTML='<h2>Your Companies</h2>'+S.countries.map(c=>`<div class="company"><b>${c.name} Industrial Group</b><br><span class="muted">Ownership ${S.holdings[c.id]||0}% • Factories ${S.factories[c.id]||0}</span><div class="bar"><i style="width:${Math.min(100,(S.holdings[c.id]||0)*2)}%"></i></div></div>`).join('');else if(t==='market')document.getElementById('panelBody').innerHTML='<h2>World Market</h2><div class="stat">Oil <b>$82</b></div><div class="stat">Iron <b>$54</b></div><div class="stat">Food <b>$31</b></div><p class="muted">Prices fluctuate as trade, wars and industrial demand change.</p>';else if(t==='politics')document.getElementById('panelBody').innerHTML='<h2>Political Theatre</h2><p>Three factions compete for power. Your influence can fund campaigns and shape industrial policy.</p><div class="stat">Industrialists <b>42%</b></div><div class="stat">Reformists <b>35%</b></div><div class="stat">Nationalists <b>23%</b></div>';else document.getElementById('close').click()});
resize();ui();